# Generated by Django 3.1.4 on 2021-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('attrs', models.JSONField(null=True)),
                ('trained_models', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'databases',
            },
        ),
        migrations.AlterField(
            model_name='explore',
            name='records',
            field=models.JSONField(null=True),
        ),
    ]
