# Generated by Django 3.1.4 on 2021-09-16 04:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0003_auto_20210914_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='intro',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
